### ISSUE TITLE
Loop when navigating back from login

### ISSUE THREAD

**Issue by whitfier** [Peppermint-Lab/Peppermint#10]
There appears to be some sort of redirect loop when navigating back on the login page.

When I'm on https://demo.pmint.dev/login, navigating back in Chrome takes me to https://demo.pmint.dev/Login. Navigating back again takes me to https://demo.pmint.dev/login, and this cycle repeats.

**Comment by potts99** [comment]
Fixed now, will be in update 0.1.6
