### ISSUE TITLE
CalDAV sync and customer database backend

### ISSUE THREAD

**Issue by xeruf** [Peppermint-Lab/peppermint#101]
I would like tools that embrace doing one thing well in the server realm, as they do on my computer. For that, the ticketing should only handle the tickets and, rather than providing these features itself, integrate with other tools to provide task overviews (CalDAV, see Nextcloud or Vikunja, where it is in the works), customer data (no idea on that, but we need our customer data in the ticketing, in our shopsystem, our HestiaCP - would be really convenient to have a backend service which has that as sole purpose) and time tracking (e.g. Kimai).
Are you aiming for something like this? We are currently playing with Zammad but are open for alternatives

**Comment by potts99** [comment]
The intention is to be a full app so in the end will be able to handle all of this in app

**Comment by xeruf** [comment]
that is unfortunate, what makes you dismiss a focus on integrations, which could make you stand out from tools like Zammad?
