### ISSUE TITLE
Deletion of users/clients

### ISSUE THREAD

**Issue by ChaseCares** [Peppermint-Lab/peppermint#102]
I think it would be nice to be able to completely remove these entities when/if they are no longer needed.

Thanks!

**Comment by potts99** [comment]
I've thought about this also, in this case, would a client's tickets remain? or would they all be deleted too? I may just add an active field and hide the ones that are set to false

**Comment by ChaseCares** [comment]
I believe that clients tickets should remain, although there could be some nuance here that I haven't fully thought through. The reason this came up is because I was testing functionality and created fictitious users and clients and now I can't get rid of them. It's not a huge issue, but something that I came across while testing, thank you!

**Comment by potts99** [comment]
Due to clients being linked by relational to a ticket unless it is isn't issued, i think the active field is the right play.

when set to false then the client wont show up in create a ticket etc

**Comment by potts99** [comment]
Added an ACTIVE Boolean to client Model in prisma schema, toggle able in admin settings, added to SQL queries to only search for clients that are ACTIVE === true

**Comment by potts99** [comment]
coming next update
