### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [Peppermint-Lab/peppermint#109]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@vultza) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by potts99** [comment]
sure thing will do

**Comment by JamieSlome** [comment]
@potts99 - thanks for creating the `SECURITY.md`.

The report can be found directly here:
https://huntr.dev/bounties/d41ca0f2-d1b2-4d41-8bc0-973fc6f02790/

It is private and only accessible to maintainers with repository write permissions 👍

**Comment by potts99** [comment]
thanks :)
