### ISSUE TITLE
Invalid login causes redirect to main page and does't display error message

### ISSUE THREAD

**Issue by igvnv** [Peppermint-Lab/Peppermint#11]
Click on `Log in` button always leads to redirect and newer displays error:
```
<Button
  ...
  onClick={() => {
    onSubmit();
    setTimeout(() => history.push("/"), 1000);
  }}
>
```

A better way is to block login button while request is sending and then redirect user or display error without refreshing and don't clean values in form. Antd buttons have `loading` attribute that looks good for this goal.

**Comment by potts99** [comment]
Thank you :) 

Will look at implementing this now

**Comment by potts99** [comment]
Added this in now, will be live in next release
