### ISSUE TITLE
[Question] Have an API

### ISSUE THREAD

**Issue by itsalb3rt** [Peppermint-Lab/peppermint#110]
Hello!

The app include an API ? 

The idea is: I have multiple apps, and I have the idea to create a unique point of true with issue in each app, imagine a user creating an issue from the app UI with an **Issue form**. If this peppermint has an API, this can be my point of true for my apps.

**Comment by potts99** [comment]
Hey, i'm slowly building out a swagger docs for the api, an up to date version can be found in src/pages/api/v1 

The create ticket endpoint is currently protected by anything and is just a post request. 
https://github.com/Peppermint-Lab/peppermint/blob/master/pages/api/v1/ticket/create.js

In theory you should be able to have forms that link to a central url - example - POST - issues.example.com/api/v1/ticket/create

Thanks for checking us out :)

**Comment by itsalb3rt** [comment]
Thanks so much!
