### ISSUE TITLE
Web Page does not load After Sign in

### ISSUE THREAD

**Issue by jpcapone** [Peppermint-Lab/peppermint#111]
After I deploy the system using the docker compose example, i am unable to connect after logging in.  The error is can't reach this page.   In the docker container log I see this in the logs:
The following migrations have been applied:

migrations/
  └─ 20220129233509_/
    └─ migration.sql
  └─ 20220130122101_/
    └─ migration.sql
  └─ 20220130225732_/
    └─ migration.sql
      
All migrations have been successfully applied.
Done in 1.84s.
yarn run v1.22.19
$ prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (3.7.0 | library) to ./node_modules/@prisma/client in 188ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```

warn Versions of prisma@3.14.0 and @prisma/client@3.7.0 don't match.
This might lead to unexpected behavior.
Please make sure they have the same version.
┌─────────────────────────────────────────────────────────┐
│  Update available 3.14.0 -> 4.3.1                       │
│                                                         │
│  This is a major update - please follow the guide at    │
│  https://pris.ly/d/major-version-upgrade                │
│                                                         │
│  Run the following to update                            │
│    yarn add --dev prisma@latest                         │
│    yarn add @prisma/client@latest                       │
└─────────────────────────────────────────────────────────┘
Done in 3.35s.
yarn run v1.22.19
$ prisma db seed
Environment variables loaded from .env
Running seed command `node prisma/seed.js` ...
{
  admin: {
    id: 1,
    createdAt: 2022-09-11T20:22:19.258Z,
    updatedAt: 2022-09-11T20:22:19.258Z,
    name: 'admin',
    password: '$2b$10$BFmibvOW7FtY0soAAwujoO9y2tIyB7WEJ2HNq9O7zh9aeejMvRsKu',
    email: 'admin@admin.com',
    isAdmin: true
  },
  internal: {
    id: 1,
    createdAt: 2022-09-11T20:22:19.264Z,
    updatedAt: 2022-09-11T20:22:19.264Z,
    name: 'internal',
    email: 'internal@admin.com',
    contactName: 'admin',
    number: '123456789',
    notes: null
  }
}

🌱  The seed command has been executed.
Done in 1.26s.
yarn run v1.22.19
      
$ next start
ready - started server on 0.0.0.0:5000, url: http://localhost:5000
info  - Loaded env from /app/.env
warn  - SWC minify beta enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error request to http://peppermint.jwtsolutions.co/api/auth/csrf failed, reason: read ECONNRESET {
  error: {
    message: 'request to http://peppermint.jwtsolutions.co/api/auth/csrf failed, reason: read ECONNRESET',
    stack: 'FetchError: request to http://peppermint.jwtsolutions.co/api/auth/csrf failed, reason: read ECONNRESET\n' +
      '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
      '    at ClientRequest.emit (events.js:400:28)\n' +
      '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
      '    at Socket.emit (events.js:400:28)\n' +
      '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
      '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
    name: 'FetchError'
  },
  path: 'csrf',
  header: {
    host: 'peppermint.jwtsolutions.co:5000',
    connection: 'keep-alive',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33',
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    referer: 'http://peppermint.jwtsolutions.co:5000/',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US,en;q=0.9',
    cookie: 'next-auth.csrf-token=2185a6d7a3eb7be7611fbe8167fd45089e6cd0d28e6f18ad0807e51d500131f3%7C21321598a39c68df3f039ea0d6e48909f009cadf61e3d89e44c0365c6ec2e7b0; next-auth.callback-url=http%3A%2F%2Fpeppermint.jwtsolutions.co%3A5000%2F'
  },
  message: 'request to http://peppermint.jwtsolutions.co/api/auth/csrf failed, reason: read ECONNRESET'
}

I notice that the instructions say to go the base url which doesnt load.  I added port  80 to the client container just to test it and it was still no go.   however I can connect when I go to 'http://peppermint.jwtsolutions.co:5000/',  I am prompted to log in but after that  I am redirected to a page that does not load.

Any suggestions would be appreciated.
Any suggestions would be appreciated.

**Comment by potts99** [comment]
can you post your docker compose file please

**Comment by jpcapone** [comment]
Thanks for getting back to me so quickly.

version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: 'postgres'
      BASE_URL: "http://peppermint.jwtsolutions.co"

**Comment by jpcapone** [comment]
Did we have any updates on this issue?  I can provide more detail if needed.

**Comment by potts99** [comment]
> Did we have any updates on this issue? I can provide more detail if needed.

Did you ever set up a reverse proxy?

**Comment by jpcapone** [comment]
I use nginx proxy manager but I haven't set it up for this instance just yet.  I wanted to get it working before implementing the reverse proxy.

**Comment by potts99** [comment]
You need to set up the reverse proxy, then will work on your sub directory, i have no issues

**Comment by BobHassok** [comment]
I am having a similar issue on a local network setup. Issue#114

**Comment by ofgrenudo** [comment]
I know that this issue is old, but for anyone looking to resolve this in the future, the issue comes from the final line of the error. 

```
},
message: 'request to http://peppermint/api/auth/csrf failed, reason: connect ECONNREFUSED 172.19.0.3:80'
}
```

Here you can see that the error is `ECONNREFUSED 172.19.0.3:80`, in the end users config the clients base URL is `BASE_URL: "http://peppermint.jwtsolutions.co/"`. which is not 172.19.0.3:80. To resolve this issue quickly, set your base url to include the port as well. 

The proper way to resolve it would be probably building a reverse proxy that would forward traffic from port 80 to the port 5000.

**Comment by potts99** [comment]
@ofgrenudo thank you for this

Will write some more docs around this

**Comment by potts99** [comment]
With the new backend api this should now no longer be an issue
