### ISSUE TITLE
Won't allow login

### ISSUE THREAD

**Issue by axelrafn** [Peppermint-Lab/peppermint#113]
When I installed the container using the Docker compose file from the website, everything installed fine but when I tried to log in, the page diverted me to localhost but on port 80 instead of the pre-defined port 5000.

I modified the docker compose file to change the outer port to 80 and installed the containers again and then it works, but it still won't let me log in.

Here is the output from the logs I see within Portainer:

> https://next-auth.js.org/errors#client_fetch_error request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80 {
>   error: {
>     message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80',
>     stack: 'FetchError: request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80\n' +
>       '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
>       '    at ClientRequest.emit (events.js:400:28)\n' +
>       '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
>       '    at Socket.emit (events.js:400:28)\n' +
>       '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
>       '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
>       '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
>     name: 'FetchError'
>   },
>   path: 'csrf',
>   header: {
>     host: 'localhost',
>     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0',
>     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
>     'accept-language': 'en-US,en;q=0.5',
>     'accept-encoding': 'gzip, deflate, br',
>     referer: 'http://localhost/auth/login?callbackUrl=http://localhost/',
>     dnt: '1',
>     connection: 'keep-alive',
>     cookie: 'connect.sid=s%3AwF77QckbhqmtJy9akC6lRmZtz3oqlRAl.DKTheyFNYuwqylj7t%2Fo%2FiA8HUf1mg23YWobmB9J8IsQ; local_adminer_session=416977; adminer_sid=a04f34ebeccb56b200f0535b2578351d; mw_installer_session=2e1c8dc537ef813f5530b2df6cff5214; next-auth.csrf-token=bf7360c31a0179441903761a1e501849a4e2c029dfb5cdb34bb43f25ec9bcabc%7Cf1a5400bc6e1f9baa5f8616e0b4cd8ad1c7e4421b4eb93951ef01da170f8e08d; next-auth.callback-url=http%3A%2F%2Flocalhost%2F',
>     'upgrade-insecure-requests': '1',
>     'sec-fetch-dest': 'document',
>     'sec-fetch-mode': 'navigate',
>     'sec-fetch-site': 'same-origin',
>     'sec-fetch-user': '?1'
>   },
>   message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80'
> }
> 
> d
> [next-auth][error][CLIENT_FETCH_ERROR] 
> https://next-auth.js.org/errors#client_fetch_error request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80 {
>   error: {
>     message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80',
>     stack: 'FetchError: request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80\n' +
>       '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
>       '    at ClientRequest.emit (events.js:400:28)\n' +
>       '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
>       '    at Socket.emit (events.js:400:28)\n' +
>       '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
>       '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
>       '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
>     name: 'FetchError'
>   },
>   path: 'csrf',
>   header: {
>     host: '127.0.0.1',
>     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0',
>     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
>     'accept-language': 'en-US,en;q=0.5',
>     'accept-encoding': 'gzip, deflate, br',
>     referer: 'http://127.0.0.1/',
>     dnt: '1',
>     connection: 'keep-alive',
>     cookie: 'next-auth.csrf-token=9a58e098a376397aa0c0d22a07043c309c20e5165dc30c50c1655e0248c5ba30%7C4b5891abb5cddfecb2ee56bb00b6fe76ae6d5efebbf660df402305290e7b6139; next-auth.callback-url=http%3A%2F%2Flocalhost',
>     'upgrade-insecure-requests': '1',
>     'sec-fetch-dest': 'document',
>     'sec-fetch-mode': 'navigate',
>     'sec-fetch-site': 'same-origin'
>   },
>   message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80'
> }
> 
> d
> [next-auth][error][CLIENT_FETCH_ERROR] 
> https://next-auth.js.org/errors#client_fetch_error request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80 {
>   error: {
>     message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80',
>     stack: 'FetchError: request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80\n' +
>       '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
>       '    at ClientRequest.emit (events.js:400:28)\n' +
>       '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
>       '    at Socket.emit (events.js:400:28)\n' +
>       '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
>       '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
>       '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
>     name: 'FetchError'
>   },
>   path: 'csrf',
>   header: {
>     host: 'localhost',
>     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0',
>     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
>     'accept-language': 'en-US,en;q=0.5',
>     'accept-encoding': 'gzip, deflate, br',
>     referer: 'http://127.0.0.1/',
>     dnt: '1',
>     connection: 'keep-alive',
>     cookie: 'connect.sid=s%3AwF77QckbhqmtJy9akC6lRmZtz3oqlRAl.DKTheyFNYuwqylj7t%2Fo%2FiA8HUf1mg23YWobmB9J8IsQ; local_adminer_session=416977; adminer_sid=a04f34ebeccb56b200f0535b2578351d; mw_installer_session=2e1c8dc537ef813f5530b2df6cff5214; next-auth.csrf-token=bf7360c31a0179441903761a1e501849a4e2c029dfb5cdb34bb43f25ec9bcabc%7Cf1a5400bc6e1f9baa5f8616e0b4cd8ad1c7e4421b4eb93951ef01da170f8e08d; next-auth.callback-url=http%3A%2F%2Flocalhost%2F',
>     'upgrade-insecure-requests': '1',
>     'sec-fetch-dest': 'document',
>     'sec-fetch-mode': 'navigate',
>     'sec-fetch-site': 'cross-site',
>     'sec-fetch-user': '?1'
>   },
>   message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80'
> }
> 
> d

The same error comes whether I am using HTTP://localhost or HTTP://127.0.0.1.

Any thoughts on what the problem might be?

**Comment by ahnafnafee** [comment]
Change `BASE_URL` in the docker-compose.yml file from `http://localhost` to **`http://localhost:5000`**

**Comment by potts99** [comment]
Thank you @ahnafnafee

**Comment by potts99** [comment]
Closing for stale
