### ISSUE TITLE
Webpage doesn't load after sign-in on local-only setup (similar to #111)

### ISSUE THREAD

**Issue by BobHassok** [Peppermint-Lab/peppermint#114]
I'm trying to test Peppermint, but whenever I try to get past the login screen it fails. This is the message that appears in peppermint's log.

[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80 {
  error: {
    message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80',
    stack: 'FetchError: request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80\n' +
      '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
      '    at ClientRequest.emit (events.js:400:28)\n' +
      '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
      '    at Socket.emit (events.js:400:28)\n' +
      '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
      '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
    name: 'FetchError'
  },
  path: 'csrf',
  header: {
    host: '10.1.10.100:5000',
    connection: 'keep-alive',
    dnt: '1',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36',
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
    'sec-gpc': '1',
    'accept-language': 'en-US,en',
    'accept-encoding': 'gzip, deflate',
    cookie: 'remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6Imo0MW5Qb2NwYWQzaXByWUFVWUlueUE9PSIsInZhbHVlIjoiekxiaDMvWkljMlVwcDNQMVA4eHR0c3lNM3FUcEhxcE9iMUZ0ZThnWENiaVhDYmhMZkx2czdxU0FTZGZtWEFKbUdnUzdiTTg2YlZyWXF0VWVZQ0w5eWZNSUZPUGw1ckJwMzRHNVg3R29qYXMzVjRDY2dXalZDZjZlNGpqZnZNTm42eml6YVlOdGJoZG9uK3QyQnloOXE5VjJDenpYaHVraGRaR0dtZHpzdGFIQzJCWTMwZjBKMnN1dkJnWThmRGgybXlXd2d3NEFKMU9xZ294S2F2Z0l5N055dHdtczN1MVBIZTNoS3daWUwxND0iLCJtYWMiOiI5MmI5MDQ1ZWRlOGQzOTA4Yzg3ZDUyYmNlMmJhMTRhZjY0OTNkNWJhZTFkMjM3NjkwMmRjOTFhNTM5MmYzYTNkIn0%3D; csrftoken=Ya4Onh3cxnKE5Oa4ZLp2yUc11wfnmtFmLJvFyeXNZMt93RzB9Ga8cJunUGNS0qm0; next-auth.csrf-token=f05e767cd8a534505311d170c7b46703c8b4cb471e1869f3b7160530c31ebff1%7C7128bcd9c5735a3aadd830771bd82599cf7fed40162cea6763da2703ff26ff3a; next-auth.callback-url=http%3A%2F%2Flocalhost'
  },
  message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80'
}

d

I'm literally just using the default docker-compose from Peppermint's website:

version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./docker-data/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: peppermint

  client:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    ports:
      - 5000:5000
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_USERNAME: peppermint
      DB_PASSWORD: 1234
      DB_HOST: 'postgres'
      BASE_URL: "http://localhost"

**Comment by potts99** [comment]
you need port on the base url so http://localhost:5000

**Comment by BobHassok** [comment]
> you need port on the base url so http://localhost:5000

I swear I tried that earlier and it didn't help. Well, it works fine now. I guess I just kept mis-typing something.

**Comment by potts99** [comment]
no worries
