### ISSUE TITLE
Delete notebook/tickets?

### ISSUE THREAD

**Issue by kmanwar89** [Peppermint-Lab/peppermint#115]
Is there a way to delete/purge old entries? For instance, I made a test notebook with just gibberish, but there is no way to delete it, even if I completely blank out the note and notebook name.

Same for tickets - let's say I make some test tickets, how can I delete them before I go to "prod"?

Thanks!

**Comment by potts99** [comment]
notebook deletion next update, ticket hiding coming next update, no adding deletion just yet for tickets

**Comment by kmanwar89** [comment]
Thank you! I really appreciate this program, and if you're accepting contributors I'd be happy to help out! I know a little bit of Python and HTML/JavaScript so I'm not sure where I could help, but please let me know if I can contribute to the project.
