### ISSUE TITLE
No persistent volume

### ISSUE THREAD

**Issue by mariushosting** [Peppermint-Lab/peppermint#118]
:**/data/db** not save in any persistent volume.
What is the exact path?

**Comment by gossamer2** [comment]
I hope you were able to get an answer for this as you posted this back in December... I just installed this today and ran in to the same issue setting it up in Docker.

The path to make persistent is "/var/lib/postgresql/data".

**Comment by mariushosting** [comment]
> I hope you were able to get an answer for this as you posted this back in December... I just installed this today and ran in to the same issue setting it up in Docker.
> 
> The path to make persistent is "/var/lib/postgresql/data".

I did in February and updated my article accordingly https://mariushosting.com/how-to-install-peppermint-on-your-synology-nas/

Thank you for replying @gossamer2 
Wish you a fantastic day!

**Comment by potts99** [comment]
@gossamer2  thank you, i'll update the path in the compose file so it is persistant by default
