### ISSUE TITLE
Changes in local source code not reflecting on the website

### ISSUE THREAD

**Issue by Mahavir-devs** [Peppermint-Lab/peppermint#119]
Hi everyone, I would like to know how can put my company logo on the website and also change the text data. I had changed the text data in app.js in the title tag and images I have just replaced them in the source folder. I have run the command docker compose --build but the changes that I have made in the source code aren't reflecting the webpage. I'm kinda new to docker stuff please kindly help.

**Comment by potts99** [comment]
you would need to run yarn run build then docker compose build for changes to take affect
