### ISSUE TITLE
Could be noob question, specific Fetch Auth API call returning 404

### ISSUE THREAD

**Issue by aabels** [Peppermint-Lab/peppermint#121]
Hello,

I really like your app, very clean and simple but sort of confused as what I am doing wrong.

I'm running locally (windows) and not using Docker. 
 
The API calls seem to work fine but there is a specific call at the UserProfile component called "async function postData()" that returns 404 for me.

(browser console)
> + PUT http://localhost:3000/api/v1/auth/profile  (404 Not Found) - breaking @ \components\UserProfile\index.js  line 27
> + VM16581:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

My senses tell me it has to do with either:
- \pages\api\auth\[...nextauth].js
- \components\UserProfile\index.js

I would like to know:
 - how does this endpoint translate properly? -> /api/v1/auth/profile

Any help or direction would be incredible.👍

**Comment by potts99** [comment]
Ah, well found, this seems to be fixed under the next branch -> if you maybe try to use that version, you should be fine.

Thank you for checking us out, working on big update soon

**Comment by aabels** [comment]
sweet deal, thanks for quick reply!
