### ISSUE TITLE
QoL issues and suggestions

### ISSUE THREAD

**Issue by FoxNBeard** [Peppermint-Lab/peppermint#122]
Hi there,
First off, great work designing a simple to use platform to manage tickets. It's been perfect for me to use as an extra tool to keep my tasks (work related or not) in an environment that I can always fall back to.

There are a few QoL issues I'd like to mention, just in case:

- When creating a ticket, after filling in all the info, when you hover the "create ticket" button it gives a "forbidden" symbol, yet still creates the ticket. Could be confusing.
- Many parts of the web interface do not have an option to "delete" (or I am missing it). I like to use the method of backup the database to a seperate location and eventually remove aged tickets, but I simply can't delete them. Same goes for users and/or clients, I can't remove them and am forced to go into the postgres db to remove them.
- Is there an option to edit a ticket to the point where you can alter the initial information like name, number, email, ticket priority (important!), etc...
- This is personal preference, but a "post" based system would be useful for "activity" where you can add a new "update" rather than edit the existing acitivity notes. It would be nice to have a timestamp along with it as well.
- Many pages do not automatically refresh after editing.
- Sometimes writing causes markdown to automatically trigger, which is fine, but the input field tends to react weird when this happens. For example, the cursor does not get displayed in the right spot, making it tricky to find where exactly you're going to be editing.

I'll add new things if I bump into them, I'm still relatively new to peppermint and have only been using it actively for a couple of days now.

**Comment by potts99** [comment]
Thank you for checking us out @FoxNBeard 

These are some great issues, some i've already rectified previously under the NEXT branch, which ive been quiet about. I want to get everything perfect before i announce anything big. 

I've jotted these down and added them to my todo list. Been actively working on issues before work in order to get into a routine, because at night i'm just too busy.

**Comment by potts99** [comment]
@FoxNBeard I have implemented many of your points now,

 - moved to a comments based system rather than & activty box.
 - Alter ticket information such as priority etc
 - Pages not data fetching correctly on route change
 - Switched from markdown to rich text
