### ISSUE TITLE
SSO Login

### ISSUE THREAD

**Issue by BijSvenNL** [Peppermint-Lab/peppermint#124]
Are there any plans for SSO?

> SSO for Admins.
> SSO for Users.

Thanks - Sven :)

ps: Is there a discord server?

**Comment by potts99** [comment]
hey mate, I have SSO working on the NEXT branch using keycloak but its not quite finished yet. 

There is but its not very active - https://discord.gg/8XFkbgKmgv

Thanks for checking us out

**Comment by potts99** [comment]
@BijSvenNL This will be released in tomorrows udpate 👍
