### ISSUE TITLE
This site can’t be reached. localhost refused to connect.

### ISSUE THREAD

**Issue by nepidaps** [Peppermint-Lab/peppermint#126]
![Screenshot 2023-03-31 121513](https://user-images.githubusercontent.com/129479084/229021223-9c509dd9-a97a-4f09-b597-88bdf2c549c3.png)

**Comment by ZanZubair96** [comment]
Are you facing this issue after the login

**Comment by nepidaps** [comment]
yes

**Comment by thebinij** [comment]
#### Console Log Before
<img width="510" alt="Screenshot 2023-03-31 at 13 13 02" src="https://user-images.githubusercontent.com/93417120/229058420-39f964a9-464e-40b1-bd7c-523cdd754428.png"/>

![output_gif](https://user-images.githubusercontent.com/93417120/229057881-a0dd3cb9-a344-47e6-a96e-61f159601d3f.gif)

####  Console Log After
<img width="600" alt="Screenshot 2023-03-31 at 13 16 20" src="https://user-images.githubusercontent.com/93417120/229055964-1608193b-532a-4215-96e0-131434c12208.png"/>

**Comment by daSubby** [comment]
Yes i had the same problem. I changed the BASE_URL into the docker-composer.yml. From http://localhost to your IP+Port.
For example
![image](https://user-images.githubusercontent.com/61833245/229067972-0c13fbee-0a1e-4758-b56e-a7ebcf95aa9e.png)

**Comment by nepidaps** [comment]
> Yes i had the same problem. I changed the BASE_URL into the docker-composer.yml. From http://localhost to your IP+Port.
> For example
> ![image](https://user-images.githubusercontent.com/61833245/229067972-0c13fbee-0a1e-4758-b56e-a7ebcf95aa9e.png)
> 

i tried this and it works! Big thanks!

**Comment by potts99** [comment]
@daSubby cheers for helping him out
