### ISSUE TITLE
Update Docker image for ARM 

### ISSUE THREAD

**Issue by Zelatrix** [Peppermint-Lab/peppermint#127]
I came across this while looking for a ticketing software to play around with since I have a Raspberry Pi I'm keen to get more use out of. I looked at the Dockerhub page and I notice that it only supports `amd64` architecture. Would it be possible to update the Docker image to run on Raspberry Pi?

**Comment by gamersi** [comment]
I have the same issue. I have tried UVDesk and it doesn't have an ARM Image too!
I hope, that this will be fixed.

**Comment by potts99** [comment]
Working on it!!

**Comment by amnesiacsardine** [comment]
Also looking forward to the arm64 build. Glad to know it's being worked on.

**Comment by Xelo** [comment]
Sounds good waiting for it thanks

**Comment by tim0n3** [comment]
I've successfully created a docker image for arm64 if you'd like to try and build one yourself or use the one I've created, it's on docker-hub tim0n3/peppermint-arm64:v1 and my PR [https://github.com/Peppermint-Lab/peppermint/pull/132](url)

**Comment by kastoreon** [comment]
any update?

**Comment by kastoreon** [comment]
> I've successfully created a docker image for arm64 if you'd like to try and build one yourself or use the one I've created, it's on docker-hub[ tim0n3/peppermint-arm64:v1 ](https://hub.docker.com/r/tim0n3/peppermint-arm64) and [my PR](https://github.com/Peppermint-Lab/peppermint/pull/132)

Can confirm it works on HETZNER CAX11. With the following docker-compose.yml. Though, I need to test if I can create users, etc.

`version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/data/db
    environment: 
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: reducted
      POSTGRES_DB: peppermint
    networks:
      - peppermint

  client:
    container_name: peppermint
    image: tim0n3/peppermint-arm64:v1
    #ports:
    #- 5001:5001
    restart: on-failure
    depends_on:
      - postgres
    environment:
      PORT: 5001
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "reducted"
      DB_HOST: "postgres"
      BASE_URL: "https://support.domain.com"
    networks:
      - peppermint
      - npm_default

networks:
  npm_default:
    external: true
  peppermint:
`

![Untitled](https://github.com/Peppermint-Lab/peppermint/assets/36232657/cb8b5e20-d78c-4c03-aad7-a43aa18c1cd6)


Note: Behind the NGINX Reverse proxy I had to change the BASE_URL to https.

**Comment by potts99** [comment]
arm release now live, reverse proxy should have no issues either

**Comment by gamersi** [comment]
`linux/arm/v7` is still missing so it can only run on 64 bit arm.
