### ISSUE TITLE
Cannot create new clients.

### ISSUE THREAD

**Issue by r0073d-l053r** [Peppermint-Lab/peppermint#134]
Every time I attempt to create a new client, once I click "Save" it will refresh the page and nothing is saved.

**Comment by potts99** [comment]
Do you get any error messages in the console?

**Comment by Ginkonui** [comment]
I am encountering the same issue.

Changing browsers from Firefox (113.0) to Brave (I'm guessing any Chromium browser) helped.

**Comment by kastoreon** [comment]
Can confirm aswell, on latest Firefox 113.0 (64-bit) it does not work.

![image](https://github.com/Peppermint-Lab/peppermint/assets/36232657/1b689084-4044-4266-8711-37121ebfe1a2)

on chromium Version 113.0.5672.64 (Official Build, ungoogled-chromium) (64-bit) the above does not exist.

**Comment by voloanon** [comment]
Changing browsers does help, but I can only create one user. Its when I go to create the second user that it does the refresh but no change.

**Comment by potts99** [comment]
This is now sorted, beta coming tomorrow

**Comment by potts99** [comment]
This is now fixed, removed modal & created page to do this

**Comment by Bouni** [comment]
I encounter the exact same problem with creating users using the latest docker image `image: pepperlabs/peppermint:latest` which gives me version `0.2.4`

Firefox 114.0.2 doesn't work, Chrome 114.0.5735.199 works fine.
