### ISSUE TITLE
Allow user registration

### ISSUE THREAD

**Issue by merval** [Peppermint-Lab/peppermint#135]
There should be a way to register yourself as a new client/user

**Comment by jack00693** [comment]
Great suggestion! I second that

**Comment by potts99** [comment]
Great suggestion, will work on this tonight!!

**Comment by void4121** [comment]
any idea when this may be a feature?

**Comment by andersmmg** [comment]
Is this still planned?

**Comment by b6user** [comment]
I think this would be great if possible. From installing it my understanding is that the use who submitted a ticket can’t login? It’s just the admins?

**Comment by potts99** [comment]
hi @b6user im working on a client portal at the moment for tracking and managing their own tickets

**Comment by potts99** [comment]
This feature is now available on latest version 👍
