### ISSUE TITLE
Translation English to French

### ISSUE THREAD

**Issue by stephane-couget** [Peppermint-Lab/peppermint#136]
Hello to all the team, I want to translate the character strings from English to French, if you have only one file, I need the copy otherwise please tell me how to do it in practice. 

Best regards,

**Comment by potts99** [comment]
Will be writting documentation for this for at the weekend

**Comment by potts99** [comment]
@stephane-couget are you still interested

**Comment by stephane-couget** [comment]
Of course, I searched your code a bit and understood by seeing two directories DE and US (from memory) with in each two json files with identical keys, that I could do the same by adding a FR folder and a json to the keys identical and with francized values. Then I may have to do something to get the language recognised.

**Comment by potts99** [comment]
That would be awesome

**Comment by potts99** [comment]
French translation added
