### ISSUE TITLE
I cannot Login 

### ISSUE THREAD

**Issue by Solo509HT** [Peppermint-Lab/peppermint#137]
Hello  All ,
I am trying to play around with Peppermint but I  can't log in after installing it.
 He gives a connection  REFUSED. I used a different browser, and the same result occured. Any help will be gladly appreciated it.

**Comment by shrtkv** [comment]
I added the port into the BASE_URL string value ( BASE_URL: "http://localhost:5000" ),it would be better reading the PORT variable, yet I'm a noob :P

#133

**Comment by shrtkv** [comment]
@Solo509HT 

try to change the last line to

BASE_URL: "http://192.168.2.10:5000"

the number after : must be equal to the value in enviroment : PORT:

**Comment by Solo509HT** [comment]
Thank you.

**Comment by potts99** [comment]
Thanks for the help, looking to make this process a lot easier as it causes so many issues
