### ISSUE TITLE
Can't create a User

### ISSUE THREAD

**Issue by HartoMedia** [Peppermint-Lab/peppermint#140]
I tried everything in the GUI, tried it multible times. I just don't know. send help

**Comment by DoktorIgnoranz** [comment]
Hi,

I encountered the same issue while using Firefox. However, I was able to successfully create a user account using Safari on a Mac. I would recommend trying a different browser to see if that resolves the issue.

**Comment by rainyskye** [comment]
Was able to reproduce the issue on the latest version of Firefox for macOS (114.0)

Safari works though?

**Comment by potts99** [comment]
@rainyskye removed modal in latest update for this and baked in UI so shouldnt be an issue going forward 👍
