### ISSUE TITLE
Is peppermint still actively maintained? (Project dead?)

### ISSUE THREAD

**Issue by Rabenherz112** [Peppermint-Lab/peppermint#143]
Hey there,

It seems that the project is not actively maintained anymore, with still open security vulnerabilities since July 2022 (https://github.com/Peppermint-Lab/peppermint/issues/105, https://github.com/Peppermint-Lab/peppermint/issues/106). Additionally, when looking at the dependencies in the package.json file, most dependencies are outdated.

**Comment by potts99** [comment]
Hey mate, no not dead, new beta for next major udpate coming sunday
