### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by stevenFrozt** [Peppermint-Lab/peppermint#147]
When logging In, I encountered an error message:

`message: 'request to http://peppermint/api/auth/csrf failed, reason: connect ECONNREFUSED'`

After further investigation, I found that the base URL specified in the docker-compose.yml file differs between the official website and the Peppermint-lab GitHub repository.

Official Website (https://docs.peppermint.sh/): BASE_URL is mentioned as "http://localhost"
GitHub Repository: BASE_URL should be "http://localhost:5000"
To resolve this inconsistency, I suggest updating the docker-compose.yml file in the repository to reflect the correct base URL:

❌ BASE_URL: "http://localhost"
✅ BASE_URL: "http://localhost:5000"

This change will ensure the requests are sent to the correct address and resolve the connection issue.

Thank you for your attention to this matter.

**Comment by potts99** [comment]
Working on moving away from next auth which should remove this issue, should be finished tonight
