### ISSUE TITLE
SSO Documentation

### ISSUE THREAD

**Issue by Jab2870** [Peppermint-Lab/peppermint#149]
Hi,

I am really interested in having a play with this. I see in #58 that you mentioned SSO was being worked on and the fat that's it's closed, I hope means that it is implemented? I was wondering if there's any documentation anywhere explaining how to set it up / how it's been implemented.

I use [Authentik](https://goauthentik.io/) as my identity provider.

**Comment by potts99** [comment]
Docs update is in the works, just takes some time

**Comment by FreeDurok** [comment]
Hi! 
I am also very interested in the sso functionality, I use keycloak, I have searched the branches but I didn't locate in the commits the implementations, are they already ready in some branch or still need to be pushed!!!? Thanks and congratulations on the project! :)

**Comment by hakan-77** [comment]
Super exciting feature. I hope Oauth2 will be configurable and not for Keycloak only.

**Comment by potts99** [comment]
done
