### ISSUE TITLE
Proxy Issues 

### ISSUE THREAD

**Issue by fuzzyone82** [Peppermint-Lab/peppermint#155]
Hello.  recently setup a Ubuntu server for Peppermint. I set up a free Cloud flare  so I can get to my stuff via tunnels.  For some reason, I am having issues setting this up. I tried going through the documentation you provided (https://docs.peppermint.sh/proxy#checking-nginx)  but it's not letting me do this. So I can go to, for reference, www.ubuntu.com, and it will go to the login page, but it still lists my LAN IP address as a "callback URL." Then, after I login, it just displays my IP address. I tried clearing the cache. I even tried going to a remote computer; I could get to the login, but after that, it errors out saying can't find page.  Any information on this would be helpful.

**Comment by potts99** [comment]
Working on moving away from next auth which should remove this issue
