### ISSUE TITLE
Cannot delete tickets or history of said ticket

### ISSUE THREAD

**Issue by daveyloder** [Peppermint-Lab/peppermint#161]
Having issue trying to delete ticket history and trying to delete ticket. Any ideas?

**Comment by potts99** [comment]
why would you want to do that?

**Comment by daveyloder** [comment]
If testing the app or if entry is invalidOn Aug 30, 2023, at 6:51 PM, Jack Andrews ***@***.***> wrote:﻿
why would you want to do that?

**Comment by potts99** [comment]
Hmm i might make this an admin only feature

**Comment by daveyloder** [comment]
That would be exactly the idea and would be coolOn Aug 31, 2023, at 5:31 AM, Jack Andrews ***@***.***> wrote:﻿
Hmm i might make this an admin only feature

**Comment by slinky1914** [comment]
This feature would be awesome and I agree only admins should be able to do it. I created a ticket with the wrong name and now I cant edit it or delete. Thank you.

**Comment by potts99** [comment]
Ability to hide ticket is building now and will be on latest tag shortly @slinky1914 @daveyloder
