### ISSUE TITLE
Forwarding issue

### ISSUE THREAD

**Issue by Vexet83** [Peppermint-Lab/peppermint#174]
After deploying on both Linode and self-hosted, I have run into an issue where, from an external system that doesn't have access to the server IP range, I can get to the login screen, but as soon as I try logging in, it takes me to localhost:5000 or <ip>:5000 instead of straight to the dashboard. To get to the dashboard after that, I have to click the back button and delete everything after the domain name (i.e., **from**: http://support.<domain>:5000/auth/login?callbackUrl=http://localhost:5000&error=SessionRequired; **to**: http://support.<domain>:5000). It is the same when I log out. It takes me to the localhost:5000 or <IP>:5000, and I have to hit the back button to get back to the login screen. 

On the Linode deployment, I can't make any changes to it since it is all automatic, and I can't find anything within the machine to edit. I also couldn't find any documentation about the deployment. I would also like to utilize certificates for secure connections.

In the self-host, I use TrueNAS scale to deal with certs and Traefik for external access. So, whenever I set the BASE_URL to https://support.<domain> I can't even log in and do the above issue/workaround.

**Comment by whosFritz** [comment]
I got a simular issue where I get redirected to localhost http://localhost/api/auth/signin?csrf=true after login in on the dashboard for the first time. I never got to the dashboard. Accessing from outside looks like this

![error peppermint](https://github.com/Peppermint-Lab/peppermint/assets/97552289/d40834e5-a6f5-4387-9827-bb20eab882e4)

When going back through the browser I end up at an url like you but can't work around it.

**Comment by randallmorse** [comment]
I experienced this as well while trying it via the one click marketplace deploy from linode.com

**Comment by whosFritz** [comment]
make sure to change BASE_URL to ur fqdn with port in the docker-compose.yml

for example: subdomain.wikipedia.com:5000

now it works for me

**Comment by whosFritz** [comment]
I got it now working using apache2 with proxy config and running peppermint locally with docker.
I didn't use linode deploy.
Like this:

<VirtualHost *:80>
    ServerName your-fqdn

    ProxyPass / http://localhost:5000/
    ProxyPassReverse / http://localhost:5000/

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

**Comment by potts99** [comment]
next auth now removed -> should be a non issue
