### ISSUE TITLE
Navigation error

### ISSUE THREAD

**Issue by ghostdevv** [Peppermint-Lab/Peppermint#18]
Clicking on this button: https://i.imgur.com/EvFKX19.png causes issues. When you click it, it becomes the active link meaning even if you are on the home page it says that is the active link when all that does is take you to `pmint.dev`

**Comment by potts99** [comment]
Hi, I don't quite understand what you mean?

The first nav bar link labelled peppermint will always take you to pmint.dev by design

**Comment by ghostdevv** [comment]
What I mean is after clicking on it the blue line appears but since it's an external link and not one of the pages on the site it doesn't make sense for it to do so

**Comment by potts99** [comment]
ah right okay! I get you, will sort

**Comment by potts99** [comment]
Should be sorted in next update :)
