### ISSUE TITLE
Fresh install... "{"healthy":true}"

### ISSUE THREAD

**Issue by evansharp** [Peppermint-Lab/peppermint#191]
Hello, 

After getting a new install up and running, I'm just seeing the plaintext `{"healthy":true}` in the browser instead of a UI. 

I used the compose [from the docs](https://docs.peppermint.sh/). There are two different suggested `compose` files btw, ~but the one on Github looked older~ the README is presenting the 'development env' build without qualification.

I'm proxying localhost:5000 to a subdomain if that matters. Have successfully set up SSL with a LE cert on the proxy endpoint. This is a cloud instance and I intend for it to be online. 

What do?

**Comment by evansharp** [comment]
Implementing the most up to date compose file on GH, I still have this issue.

**Comment by potts99** [comment]
port 3000 @evansharp

**Comment by evansharp** [comment]
oh, 5003 is just API?

**Comment by evansharp** [comment]
I need 3000 for another application. I've mapped 3003:3000 in the compose. Now that I've moved the proxy over to 3003, I'm seeing an 'invalid' response. ideas? @potts99
