### ISSUE TITLE
Hidden tickets still count 

### ISSUE THREAD

**Issue by zhedar** [Peppermint-Lab/peppermint#193]
If a ticket is hidden, it is still counts into the dashboard counter. There's no way to view hidden tickets and to unhide an already hidden ticket, when you navigated away from its page.

So: 

- hidden tickets should be excluded from the dasboard counters
- there should be a tab for hidden tickets (for admins)
- optional: there should be a confirmation dialog before hiding a ticket

**Comment by potts99** [comment]
fixed
