### ISSUE TITLE
Newsletter page css issue

### ISSUE THREAD

**Issue by ghostdevv** [Peppermint-Lab/Peppermint#20]
https://i.imgur.com/6oThsiS.png

**Comment by potts99** [comment]
What size is this? or device?

**Comment by ghostdevv** [comment]
I not able to reproduce this again, I have got it twice but trying again not working. Odd

Though I did notice this issue: https://i.imgur.com/aIW80yO.gif

**Comment by potts99** [comment]
Should be fixed in next update release
