### ISSUE TITLE
Latest 4.1 version still installs 3.6 version?

### ISSUE THREAD

**Issue by JeremiLorenti** [Peppermint-Lab/peppermint#209]
Keep trying to install the latest build and I keep getting shown 0.3.6 installed when I get logged in. 

![msedge_fjyMmBA0yk](https://github.com/Peppermint-Lab/peppermint/assets/120612878/2fd6bac8-3c8a-4c53-a043-52a24a340ba7)

**Comment by potts99** [comment]
will sort thank you :) you are on 0.4.1 just a visual bug

**Comment by brokenbrainguy** [comment]
I can report that I'm also having this issue. Spent an hour thinking I screwed something up, but yeah, I've got the exact same interface showing ver 0.3.6. Installed using Docker on 12/15/23 @ 10:30pm EST

**Comment by potts99** [comment]
Have pushed an update to change this

**Comment by brokenbrainguy** [comment]
How long until is live and available for a docker pull?

**Comment by potts99** [comment]
live now :)

**Comment by brokenbrainguy** [comment]
I just tried reinstalling a new docker container with a new repull of pepperlabs/peppermint:latest and it's still showing 0.3.6?

**Comment by potts99** [comment]
Have you deleted the old image @brokenbrainguy

**Comment by brokenbrainguy** [comment]
Yea, deleted the images, containers, volumes, stacks. Everything and all to make sure that it would pull and install a clean version. When it started, it was still 0.3.6

**Comment by potts99** [comment]
ive just done the exact same thing and its updated for me, just to be clear the version 0.3.6 in the top left was a visual bug, and the docker latest image is correct

**Comment by brokenbrainguy** [comment]
Yeah, my inteface still looks nothing like everything I've seen in pics and videos on YouTube about it. I'm hoping that the functioning it the latest, but the interface still looks like the first posted screenshot by the original author of this thread.

**Comment by brokenbrainguy** [comment]
@potts99 Ok, Inside portainer I redid everything from deleting everything Peppermint related and event rebuilt the custom stack with the docker compose on the Github frontpage provided. Now, I have it showing 4.1 as the version, but it's missing any of the styling. Looks like the screenshot, just with the correct version number. Any idea what's causing the theme display error?
