### ISSUE TITLE
SMTP 554 Outgoing Email 

### ISSUE THREAD

**Issue by JeremiLorenti** [Peppermint-Lab/peppermint#210]
After creating a test ticket, the system tries to send an email, however I get the below 554 sendas error. 

![Docker_Desktop_T84ukVv7As](https://github.com/Peppermint-Lab/peppermint/assets/120612878/4e505c14-85ab-458d-b782-3621bf79db37)

**Comment by nimeyer22** [comment]
Hi, I think it's the same problem as mine. #207

**Comment by potts99** [comment]
This should now be working as you can update the replyto @JeremiLorenti
