### ISSUE TITLE
installed Version 0.4.1 but ui looks like 0.3.6

### ISSUE THREAD

**Issue by milon27** [Peppermint-Lab/peppermint#213]
![image](https://github.com/Peppermint-Lab/peppermint/assets/44096479/5768d7ad-eb27-430c-8f2f-4a5eb8c58058)

 i have installed Version 0.4.1 
 
![image](https://github.com/Peppermint-Lab/peppermint/assets/44096479/c818cb4a-2354-47b6-bb1b-e870b22a1eab)

using this docker compose: https://raw.githubusercontent.com/Peppermint-Lab/Peppermint/master/docker-compose.yml

**Comment by milon27** [comment]
@potts99 

hi can we help me on this issue

**Comment by casmith** [comment]
@milon27 can you provide some more details about the problem? The screenshot shows 0.4.1, which is the version you say you installed. What exactly is not working correctly?

**Comment by milon27** [comment]
the new ui is not showing, its thee old ui.

**Comment by lbhopper** [comment]
I face the same issue with the UI not reflecting changes, even though the installed version says it's correct

![image](https://github.com/Peppermint-Lab/peppermint/assets/116280844/4619bd23-5c84-4aec-95c1-80f946af4d52)

**Comment by casmith** [comment]
Did you try reloading without cache enabled? It might be that you have an old stylesheet cached. Just guessing as I am not a developer on this project.

**Comment by lbhopper** [comment]
With my case, this UI shows after a fresh install; I did not have this previously.

**Comment by lbhopper** [comment]
@potts99

**Comment by milon27** [comment]
yes, I really having trouble with this. please help me fix this issue.

**Comment by lbhopper** [comment]
Looks like some checks need to be reviewed

![image](https://github.com/Peppermint-Lab/peppermint/assets/116280844/b3273147-57f1-4963-bfce-3c2d366ca627)

**Comment by potts99** [comment]
this was a visual bug and should now be fixed
