### ISSUE TITLE
Small responsiveness issue in dashboard.

### ISSUE THREAD

**Issue by steveiliop56** [Peppermint-Lab/peppermint#228]
So as you can see in the screenshot bellow the send feedback button text is not correctly aligned. 

![Screenshot_20240214_225552_Chrome](https://github.com/Peppermint-Lab/peppermint/assets/106091011/b6e8326f-202a-4e24-b5c2-9842dae0d675)

**Comment by minskmaz** [comment]
Look forward to this. It's still not counting.

**Comment by potts99** [comment]
@minskmaz the stats are currently disabled due to a bug that caused the api proxy to fail

**Comment by potts99** [comment]
will open a separate issue
