### ISSUE TITLE
Website (peppermint.sh) faulty buttons

### ISSUE THREAD

**Issue by ByteMasterFlinki** [Peppermint-Lab/peppermint#230]
On your website I can not navigate to all the "Features" tabs.
I would like to learn more about Imap and smtp. 
I tried different browsers neither Opera, Chrome and Safari worked. 
The Mobile version (tried on Iphone with Safari) don't work (and looks a bit strange).

I hope that I don't stress you with this problem.
Have a nice day

**Comment by mark-pitblado** [comment]
Hi @ByteMasterFlinki, would you mind providing a screenshot of the button you are trying to press? I did a quick ctrl-f on the main peppermint.sh homepage and could not find the word features.

In the code, I will note that it appears to be commented out

https://github.com/Peppermint-Lab/peppermint/blob/3dec5a93d0a89a0b37d788af52f762a34c9ef3cf/apps/site/pages/index.tsx#L15C1-L20C3

**Comment by fyksen** [comment]
![image](https://github.com/Peppermint-Lab/peppermint/assets/4790633/b7561c5d-22af-4958-91ae-a6d11fdf93d6)

These are the "buttons" that doesn't work. There is no URLs connected to them.

**Comment by mark-pitblado** [comment]
Hi @fyksen! Awesome, I see where these links are not working. It appears that the pages that these links are supposed to point to don't actually exist (i.e. the documentation hasn't been written yet). Therefore, the options would be to either remove these links from `_meta.json` until the pages are live, or change the title of the links to reflect their state (something like "coming soon").

That's a call only the maintainers can make, but from a technical point of view this is an easy fix! If any of the maintainers see this, if you just let me know in a comment which route you want to go I can build the PR!
