### ISSUE TITLE
UI colours different to repository screenshots

### ISSUE THREAD

**Issue by Luke0zade01** [Peppermint-Lab/peppermint#233]
Just installed on RPi 5 and the site looks different to videos and screenshots I have seen?

Is this a new look in a recent update or have I done something wrong?

Mine looks like:
![image](https://github.com/Peppermint-Lab/peppermint/assets/117951673/dd7beb61-4b63-4e75-8096-2c37cd8460c0)

Others look like:

![image](https://github.com/Peppermint-Lab/peppermint/assets/117951673/c9a298be-4f3f-40ce-8e04-a31bd3edc1b2) (NetworkChuck vid)

Sorry if I've missed something obvious.

**Comment by potts99** [comment]
Youre on the correct version! @Luke0zade01 

copy needs updating
