### ISSUE TITLE
Idioma pt-BR

### ISSUE THREAD

**Issue by j7info** [Peppermint-Lab/peppermint#238]
Gostaria de ajudar com a tradução, pois não está totalmente traduzida. Como posso ajudar?

**Comment by potts99** [comment]
Hey man, 

Peppermint uses json based translation files 

https://github.com/Peppermint-Lab/peppermint/tree/master/apps/client/locales

You would need to make a folder called BR -> then copy and paste a json file from ES/EN/PR etc and change the values to fit
