### ISSUE TITLE
OIDC Auth

### ISSUE THREAD

**Issue by potts99** [Peppermint-Lab/peppermint#267]

**Comment by Eschguy** [comment]
Connecting my Authentik instance to this would be a big QOL improvement.

**Comment by potts99** [comment]
Being worked on @Eschguy

**Comment by FreeDurok** [comment]
when oidc sso will be released?? :)

**Comment by potts99** [comment]
end of june @FreeDurok

**Comment by davispuh** [comment]
Also looking for this. So it seems very soon we will have it?

**Comment by larsassink** [comment]
We are in the end of August and still not available?

**Comment by potts99** [comment]
This is now implemented
