### ISSUE TITLE
User experience feels off when clicking 'Tickets' in the navigation bar

### ISSUE THREAD

**Issue by sahmed007** [Peppermint-Lab/Peppermint#27]
The 'Home', 'History', and 'Admin' links in the navigation bar take you to some page when clicked on them. The 'Tickets' link has a drop down which causes the navigation flow to feel a bit off. Perhaps it would be better to also make the 'Tickets' link clickable so that when clicked, it can take you to the 'Open Tickets' by default.

**Comment by potts99** [comment]
Should be sorted in next update :)
