### ISSUE TITLE
Error when docker-compose up

### ISSUE THREAD

**Issue by taiyou1116** [Peppermint-Lab/peppermint#293]
Hello😄

I was trying to launch this project locally, following the instructions in the README to run `docker-compose up --build`. 
However, I encountered the following error and am struggling to understand the cause. If anyone knows why this might be happening, could you please explain it to me?

docker-compose up
[+] Running 2/0
 ✔ Container peppermint_postgres  Created                                                                                                        0.0s 
 ✔ Container peppermint           Created                                                                                                        0.0s 
Attaching to peppermint, peppermint_postgres
peppermint_postgres  | 
peppermint_postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
peppermint_postgres  | 
peppermint_postgres  | 2024-04-07 00:12:40.170 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
peppermint_postgres  | 2024-04-07 00:12:40.177 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
peppermint_postgres  | 2024-04-07 00:12:40.177 UTC [1] LOG:  listening on IPv6 address "::", port 5432
peppermint_postgres  | 2024-04-07 00:12:40.194 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
peppermint_postgres  | 2024-04-07 00:12:40.219 UTC [29] LOG:  database system was shut down at 2024-04-07 00:04:43 UTC
peppermint_postgres  | 2024-04-07 00:12:40.275 UTC [1] LOG:  database system is ready to accept connections
peppermint           | 2024-04-07T00:12:41: PM2 log: Launching in no daemon mode
peppermint           | 2024-04-07T00:12:41: PM2 log: App [client:0] starting in -fork mode-
peppermint           | 2024-04-07T00:12:41: PM2 log: App [api:1] starting in -fork mode-
peppermint           | 2024-04-07T00:12:41: PM2 log: App [client:0] online
peppermint           | 2024-04-07T00:12:41: PM2 log: App [api:1] online
peppermint           | > client@1.0.0 start
peppermint           | > next start
peppermint           | Segmentation fault
peppermint           | 2024-04-07T00:12:43: PM2 log: App [client:0] exited with code [139] via signal [SIGINT]
peppermint           | 2024-04-07T00:12:43: PM2 log: App [client:0] starting in -fork mode-
peppermint           | 2024-04-07T00:12:43: PM2 log: App [client:0] online
peppermint           | > client@1.0.0 start
peppermint           | > next start
peppermint           | Error: Command failed: npx prisma migrate deploy
peppermint           | Segmentation fault
peppermint           |     at genericNodeError (node:internal/errors:984:15)
peppermint           |     at wrappedFn (node:internal/errors:538:14)
peppermint           |     at ChildProcess.exithandler (node:child_process:422:12)
peppermint           |     at ChildProcess.emit (node:events:518:28)
peppermint           |     at maybeClose (node:internal/child_process:1105:16)
peppermint           |     at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
peppermint           |   code: 139,
peppermint           |   killed: false,
peppermint           |   signal: null,
peppermint           |   cmd: 'npx prisma migrate deploy'
peppermint           | }
peppermint           | Segmentation fault
peppermint           | {"level":50,"time":1712448764410,"pid":19,"hostname":"cf9eadfde585","err":{"type":"Error","message":"Command failed: npx prisma migrate deploy\nSegmentation fault\n","stack":"Error: Command failed: npx prisma migrate deploy\nSegmentation fault\n\n    at genericNodeError (node:internal/errors:984:15)\n    at wrappedFn (node:internal/errors:538:14)\n    at ChildProcess.exithandler (node:child_process:422:12)\n    at ChildProcess.emit (node:events:518:28)\n    at maybeClose (node:internal/child_process:1105:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:305:5)","code":139,"killed":false,"signal":null,"cmd":"npx prisma migrate deploy"},"msg":"Command failed: npx prisma migrate deploy\nSegmentation fault\n"}

**Comment by potts99** [comment]
unsure of why youre getting a prisma seg fault @taiyou1116 have you tried rebuilding?

**Comment by potts99** [comment]
https://github.com/prisma/prisma/issues/10649
https://github.com/prisma/prisma/issues/17946

maybe related
