### ISSUE TITLE
Editing Notebooks

### ISSUE THREAD

**Issue by patrickramp** [Peppermint-Lab/peppermint#316]
Great project! One issue I have noticed is there does not appear to be a way to edit the title of a notebook or completely delete a notebook. I am not sure if I am just missing something. If I am just overlooking this feature, it would be nice if it were a bit more obvious.

**Comment by potts99** [comment]
No youre correct, will add this func @patrickramp

**Comment by potts99** [comment]
notebooks are being rethought completely, going to close this
