### ISSUE TITLE
Log in issue in dev mode

### ISSUE THREAD

**Issue by pabrodez** [Peppermint-Lab/Peppermint#32]
Hi,

I've cloned the repo and started the dev mode. When I try to log in using admin@admin.com and 1234 as user-password, I get this error on console:
`POST http://localhost:5000/api/v1/auth/login [HTTP/1.1 422 Unprocessable Entity 5ms]`

This is my `example.env` file:
`NODE_ENV=development
PORT=5000
MONGO_URI_DEV=mongodb://127.0.0.1:27017/
MONGO_URI_DOCKER=
JWT_SECRET=""`

Unfortunately, I'm not entirely sure what I've done wrong.  Do you know where could I start taking a look? Thanks.

**Comment by potts99** [comment]
hello 

for example my .env file looks like this

NODE_ENV=development
PORT=5000
MONGO_URI_DEV="mongodb://localhost:27017/peppermint"
MONGO_URI_DOCKER="mongodb://mongo:27017/peppermint"
JWT_SECRET="random key goes here"

**Comment by pabrodez** [comment]
Thank you for your suggestion. I've re-cloned, re-installed dependencies and used those env variables after starting mongo.
I had an issue where the `config > DB.js` wasn't reading the `.env`. I've changed the line:
`require("dotenv").config({ path: path.resolve(__dirname, "./config/.env") });`
to
`require("dotenv").config({ path: path.resolve(__dirname, "./example.env") });` and it does read the variables.

However, after starting the dev server I get the same error when attempting to log in:
`POST http://localhost:5000/api/v1/auth/login [HTTP/1.1 422 Unprocessable Entity 5ms]`

I don't if somebody else has had the same issue, or it might be a problem with my environment. (Btw, just trying to get it to work so I'm able to contribute to the project  : )

**Comment by potts99** [comment]
can you hop in our discord, another member has just spun up a dev environment correctly. Can jump in a call with you https://discord.gg/bqj4FuP2

**Comment by potts99** [comment]
@pabrodez will update the docs with the problem -> cheers
