### ISSUE TITLE
UI on Mobile

### ISSUE THREAD

**Issue by 1lazyprogrammer** [Peppermint-Lab/peppermint#324]
![image](https://github.com/Peppermint-Lab/peppermint/assets/163859365/109449f2-f0c8-45fe-9d7b-679ee55df89c)

**Comment by potts99** [comment]
whats the problem @1lazyprogrammer, is it a scroll issue?

**Comment by 1lazyprogrammer** [comment]
> whats the problem @1lazyprogrammer, is it a scroll issue?

First of all, thank you for your fast response.

The problem is the layout; maybe you need to change some CSS.

![image](https://github.com/Peppermint-Lab/peppermint/assets/163859365/44dc691c-c133-4f29-9a79-8469e4c74175)

By the way, I really like your open-source ticketing system. It has a beautiful UI! :) 

Could you maybe improve the documentation for me it's a littel hard to sometimes understand how I should do some things for example the e-mail functions of your ticketing system ?

I wish you a nice day:)

**Comment by potts99** [comment]
i see! yeah the mobile ui is more of an afterthought at the moment, needs a bit of tlc. Documentation is being worked on.
