### ISSUE TITLE
Blank Sender in send Mails

### ISSUE THREAD

**Issue by HauptlingHD** [Peppermint-Lab/peppermint#331]
Not sure if I made an error or overlooked something, or if it is a general bug/missing feature. Mails that are sent over SMTP are missing a username or ‘from’ address. Therefore, mails look extremely suspicious and can’t be replied to.

It would be nice if the mails would contain the address that was used to send them, and/or if the username that shows up as the sender would be configurable in the admin UI.

**Comment by potts99** [comment]
Looking into this @HauptlingHD

**Comment by HauptlingHD** [comment]
I tried again with the newest release. I am not sure if something was done already to fix this bug, but it seems to be fixed.

**Comment by potts99** [comment]
yeah this was fixed iirc @HauptlingHD
