### ISSUE TITLE
Dashboard: Open, Completed, and Unassigned counts remain zero

### ISSUE THREAD

**Issue by greigm** [Peppermint-Lab/peppermint#335]
As per description, on the dashboard, the clickable counts for the ticket categories remain zero no matter the number or state of tickets in the system.

This is a new install in a docker container - my only local config has been to configure two users and IMAP + SMTP.

**Comment by potts99** [comment]
I know about it, tempted disabled the stats as was causing an issue with loading, looking into it 🫡

**Comment by potts99** [comment]
fixed and now live @greigm

**Comment by greigm** [comment]
You, sir, are an absolute legend. Thank you. This has got to be one of the most responsive and "positive attitudey" (it's a word now) projects I've ever seen.

**Comment by potts99** [comment]
I'm a miserable mid twenties british man at heart @greigm
