### ISSUE TITLE
Name and email not displayed in ticket view

### ISSUE THREAD

**Issue by andlil** [Peppermint-Lab/peppermint#343]
Name and email entered in create ticket is not displayed in ticket view

![Skärmbild 2024-06-19 084408](https://github.com/Peppermint-Lab/peppermint/assets/10003475/283c98cf-752f-49e2-b82b-8cbc13006973)
![Skärmbild 2024-06-19 084433](https://github.com/Peppermint-Lab/peppermint/assets/10003475/bcc596a1-0329-446b-b60c-2f8604c5165e)

**Comment by SK-Crow** [comment]
+1

Would love to have some details of the user.  I did notice it shows in the webhook if you have that configured.

![image](https://github.com/user-attachments/assets/33ea5f34-0a5f-468e-8e34-359ea3926706)

**Comment by sccsspnk** [comment]
Please add the ability to show Email for administrators, but limit it to regular users of the system and also make it possible to add permission for some non-administrators

**Comment by potts99** [comment]
fixed original issue @SK-Crow @sccsspnk

**Comment by potts99** [comment]
will open seperate issues for both
