### ISSUE TITLE
Ticket title and number mismatch (caching issue probably)

### ISSUE THREAD

**Issue by Mo187** [Peppermint-Lab/peppermint#346]
Better to just open an issue directly.

Issue :
Noticed on day 1 of using peppermint, when you click on different tickets to view them it will often display the wrong ticket title and number. I have reproduced this multiple times. For example : on these two screenshots you can see that the ticket with laptop is  but when i click on the email ticket this is what it shows.
![342055352-d22f657f-7f08-418a-8391-4c4e50060695](https://github.com/Peppermint-Lab/peppermint/assets/17753184/b35a62ab-6351-43c4-8627-97c8e8aac303)
![342055357-0d78c563-0d43-4901-919a-b26f03037a70](https://github.com/Peppermint-Lab/peppermint/assets/17753184/4728746e-1b12-430b-bfc1-cbf15368511a)

**Comment by OOCAZ** [comment]
I am having this same issue, appears to be picking up the latest ticket title not the current one. I am currently on 0.4.9

**Comment by potts99** [comment]
Looking into this now, looks to be a prod only issue, apologies

**Comment by potts99** [comment]
fixed @OOCAZ @Mo187 - deployed to latest :)
