### ISSUE TITLE
(Update docs?) Health check failing due to unset BASE_URL

### ISSUE THREAD

**Issue by cyhyraethz** [Peppermint-Lab/peppermint#352]
The docs use the `API_URL` environment variable in the docker compose file, but the health check uses `BASE_URL` which is not set anywhere. When I renamed `API_URL` to `BASE_URL` the health check started passing and the container shows `healthy` status.

Is it possible there was a change at some point to the name of the environment variable being used and the docs were updated in one place but not the other, causing the health check to reference an unset environment variable?

**Comment by potts99** [comment]
docs need an update ye, will sort :)
