### ISSUE TITLE
Ticket submitted via /submit route returns error

### ISSUE THREAD

**Issue by hiteshdaswani** [Peppermint-Lab/peppermint#356]
Screenshot attached;

![Screenshot 2024-07-27 095137](https://github.com/user-attachments/assets/265a5e80-1d47-4848-bf8c-eca6b31347c6)
### Discussed in https://github.com/Peppermint-Lab/peppermint/discussions/351

<div type='discussions-op-text'>

<sup>Originally posted by **sudo-sein** July  8, 2024</sup>
I used /submit route to test the anonymous submitting functionality, and I tried to access the ticket as admin in dashboard I got following error:
"initialContent must be a non-empty array of blocks, received: This is ticket content"

Here's screenshot of details page.
![image](https://github.com/Peppermint-Lab/peppermint/assets/419502/5e3d319d-6195-4872-9b83-a976d4db168f)

Here's log console for that ticket.
![image](https://github.com/Peppermint-Lab/peppermint/assets/419502/91f96c97-146b-456e-8030-93b5443f37a4)

Seems to me like new submissions are not escaped correctly.</div>

**Comment by Spectroxx** [comment]
Discussed also in https://github.com/Peppermint-Lab/peppermint/issues/338

**Comment by Legomountain14** [comment]
same issue here.

**Comment by hiteshdaswani** [comment]
I moved to ESPOCRM, way better than  peppermint and easier to setup.

**Comment by Legomountain14** [comment]
Any update on this?

**Comment by hiteshdaswani** [comment]
i went with ESPOCRM instead, much better than peppermint.
i have it working for a month now, no problems, super stable.


---------------------------
*Hitesh Daswani*
*IT Consultancy*
E-ID : ***@***.***
Mobile Personal: +599-96726748

**Comment by potts99** [comment]
This is now fixed
