### ISSUE TITLE
Opening Recent Ticket to review and assign error

### ISSUE THREAD

**Issue by zweimalk** [Peppermint-Lab/peppermint#364]
After clicking on recent ticket there is a error message :
**Application error: a client-side exception has occurred (see the browser console for more information).**
In browser console:
**Error: initialContent must be a non-empty array of blocks, received: ***** ** from next.sj

**Comment by ZeeroMX** [comment]
I have this error too, not sure what I can do about it, tried several things but no clue why its happening.

**Comment by jniedens365** [comment]
I have the same error as well. Is there a way to change the docker compose file to download an older image of peppermint?

**Comment by quinb96** [comment]
> I have the same error as well. Is there a way to change the docker compose file to download an older image of peppermint?

I've tried the pepperlabs/peppermint:test tag and it put me on version 4.3. That error went away for me after that. I'm hoping an update will come out soon to fix this. From what I can see this error started on either 4.8 or 4.9.

**Comment by jniedens365** [comment]
That is what I did as well, but it appears the incoming email part is broken on 4.3.

**Comment by potts99** [comment]
Looking into this issue now

**Comment by potts99** [comment]
building into latest release now, apologies about the delay on this

**Comment by partha51613** [comment]
This bug has reappeared on `0.5.5.5 (nightly)`

![image](https://github.com/user-attachments/assets/751ae203-542f-4e03-bc61-e6984a478e9a)

**Comment by potts99** [comment]
How can this be recreated?

**Comment by potts99** [comment]
patched @partha51613
