### ISSUE TITLE
Having trouble trying to connect

### ISSUE THREAD

**Issue by ITKeviin** [Peppermint-Lab/peppermint#372]
I got docker and docker-compose running and docker-compose is running the yml. I used docker ps to make sure it was running. However I'm not sure what IP to use I used my IPV4 and IPV6 with the port number 5003 and it just sent me to a blank json that says Healthy : true. 

Am I missing something? Does docker have its own ip im supposed to use?

**Comment by potts99** [comment]
FE is port 3000, youre hitting the api which is hosted on 5003 :) 👍

**Comment by ITKeviin** [comment]
> FE is port 3000, youre hitting the api which is hosted on 5003 :) 👍

Worked first try lol It was 4am and my brain wasnt working I guess. thank you so much lol

**Comment by potts99** [comment]
no worries bud
