### ISSUE TITLE
OIDC "Account Not Found"

### ISSUE THREAD

**Issue by Eschguy** [Peppermint-Lab/peppermint#380]
After setting up Authentik as my SSO provider using the docs (https://docs.peppermint.sh/oidc), when attempting to log in as a user with permission to the app, the redirect goes to https://DOMAIN/auth/login?error=account_not_found

Making a local account to match does not work, but with OIDC, account creation upon login should be possible, but I don't see an option for it.

**Comment by potts99** [comment]
Hi, docs need to be update to add a little more info, you need type to be set as public in your oidc provider settings 👍 
![image](https://github.com/user-attachments/assets/d4872c4b-74ca-4b4b-bf95-c00a04fcd693)

**Comment by potts99** [comment]
if this doesn't work, please can you docker logs peppermint when trying to log in and see what it spits out at you

**Comment by Eschguy** [comment]
> Hi, docs need to be update to add a little more info, you need type to be set as public in your oidc provider settings 👍 ![image](https://private-user-images.githubusercontent.com/45759583/378343674-d4872c4b-74ca-4b4b-bf95-c00a04fcd693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1MzYyMTAsIm5iZiI6MTcyOTUzNTkxMCwicGF0aCI6Ii80NTc1OTU4My8zNzgzNDM2NzQtZDQ4NzJjNGItNzRjYS00YjRiLWJmOTUtYzAwYTA0ZmNkNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDE4MzgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjN2U2ZGYyOWFiNDYyZTA4NjQxOGVhYmJjZGQxNzk1YWEzMTYxMzQxNWFmNTgzOTBiMmNjNjMxMDRmY2YwNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JmuJHM_saKLs3eahhsPOTIBzKKjgWtyokQceoXvDZO0)

This did the trick, thanks!

**Comment by potts99** [comment]
no worries, i have updated the docs also 👍
