### ISSUE TITLE
Portal Url not opening incognito browser

### ISSUE THREAD

**Issue by partha51613** [Peppermint-Lab/peppermint#381]
Hello,

I am trying to open the guest authentication portal ```http://<ip>/submit```  on an incognito button but I get redirected to ```http://<ip>/auth/login```.

A guest user will not have an account on the portal and they will not be able to submit tickets.

Version: **0.5.2**

**Comment by SK-Crow** [comment]
I am having the same issue.  If I am not signed in, the /submit page redirects to the login page. 

Version: 0.5.2
Browsers: Chrome, Brave (Incognito, as well as just signing out)

**Comment by SK-Crow** [comment]
Logs weren't that helpful either:

![image](https://github.com/user-attachments/assets/d9589460-67ac-466e-a92e-8ea01b3c4406)

**Comment by potts99** [comment]
investigating @SK-Crow

**Comment by potts99** [comment]
This is now fixed :)
