### ISSUE TITLE
Unknown Sender from automated 'new ticket' emails

### ISSUE THREAD

**Issue by SK-Crow** [Peppermint-Lab/peppermint#389]
![image](https://github.com/user-attachments/assets/f75eb45b-6e2a-47e8-852d-219a40e06c57)

The system that handles new ticket assignment emails is sending from "unknown@unknown.com" instead of the username (email address) that I configured in SMTP & Email Queues settings.

I am using "Other" instead of Gmail or Microsoft email services.

Worth noting this is not applicable to emails generated to end users, only to system users who receive the automated "new ticket" type emails.

**Comment by potts99** [comment]
fixed 👍
