### ISSUE TITLE
Static ticket height on screen pushes comments to the bottom

### ISSUE THREAD

**Issue by SK-Crow** [Peppermint-Lab/peppermint#401]
Any chance the ticket screen could be changed from a static height to a dynamic one?  Would love to see the comments section without having to scroll.  

Example:
![image](https://github.com/user-attachments/assets/6f4cae2c-c107-477c-8186-694342d5d4bd)

Current:
![image](https://github.com/user-attachments/assets/6af2e296-c3bb-4def-bfcc-029f23403520)

**Comment by potts99** [comment]
added a max height to imap based emails with a scroll 👍 is in nightly now, will be in main couple days
