### ISSUE TITLE
OIDC Authentik OpenID Configuration Issuer redirecting to non existing URL

### ISSUE THREAD

**Issue by Thobov** [Peppermint-Lab/Peppermint#402]
First I want to thank you for implementing OIDC for Peppermint.
However, I believe there is an bug regarding OpenID Configuration Issuer.

I followed the setup at https://docs.peppermint.sh/oidc
When you create an Issuer URL for Peppermint, Authentik gives me https://redacteddomain.com/application/o/peppermint/ but Peppermint expects https://redacteddomain.com/application/o/authentik/ as you can see in my Docker log below.

`Authentication error: RPError: unexpected iss value, expected https://redacteddomain.com/application/o/authentik/, got: https://redacteddomain.com/application/o/peppermint/
    at Client.validateJWT (/apps/api/node_modules/openid-client/lib/client.js:958:15)
    at Client.validateIdToken (/apps/api/node_modules/openid-client/lib/client.js:793:60)
    at Client.callback (/apps/api/node_modules/openid-client/lib/client.js:532:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.<anonymous> (/apps/api/dist/controllers/auth.js:392:26)`

As far as I can see, there is not an option to adjust the OpenID Configuration Issuer URL.
Thus, I get an account error - account is not found in the GUI of Peppermint.

Yes, I also setup #380 as well. My Peppermint is able to contact Authentik behind my reverse proxy correctly.

Please feel free to reach out so I can provide you with the neccesary information so resolve this issue.
Thank you for reading and for your time.

**Comment by potts99** [comment]
Balls thought I'd resolved this issue

**Comment by potts99** [comment]
hmm this is my local set up that i use for local development 

```
http://localhost:9000/application/o/peppermint/.well-known/openid-configuration
```

<img width="1276" alt="Screenshot 2024-11-10 at 19 44 11" src="https://github.com/user-attachments/assets/94afeb72-ed22-4f99-90a3-21c58fd83197">

**Comment by potts99** [comment]
example of jwt payload

<img width="967" alt="Screenshot 2024-11-10 at 19 46 12" src="https://github.com/user-attachments/assets/8441724d-4f36-40c7-9d23-24292ee5c903">
