### ISSUE TITLE
replyto not being detected.

### ISSUE THREAD

**Issue by GoobyFRS** [Peppermint-Lab/peppermint#404]
Howdy - I have an issue with the nightly build where the replyto does not work as expected. I notice the following output when I send myself a reply. It does not appear to be getting linked.

I have attempted to modify the subject line to ref:#<ticket_id> and solely the <ticket_id>} and it did not work either. Otherwise sending and listening to my gmail box works as expected.

Anything I can do to help diagnose?

using command:  sudo docker logs -f peppermint

```shell
  email: 'REDACTED',
  note: null,
  isComplete: false,
  priority: 'Low',
  linked: null,
  fromImap: true,
  Number: 37,
  status: 'needs_support',
  type: 'support',
  hidden: false,
  createdBy: null,
  locked: false,
  teamId: null,
  clientId: null,
  userId: null
}
```

**Comment by potts99** [comment]
This has been reported by a couple members, I'm looking into it 👍

**Comment by potts99** [comment]
This should now be fixed on nightly 👍 will push to main shortly
