### ISSUE TITLE
Users can delete tickets from admins

### ISSUE THREAD

**Issue by noaspect** [Peppermint-Lab/peppermint#411]
It's a user account created by admin, whose role has been set to user.
When logged in as a user, I can edit tickets from other users like admin, and can even delete them.
And btw, should normal users have the power to reassign a ticket?
![image](https://github.com/user-attachments/assets/c51561e0-29fd-4527-9471-4de7f6062dfd)

**Comment by potts99** [comment]
Good spot! will amend now

**Comment by potts99** [comment]
have patched: new build is processing now 👍 i have restricted to admins only for now
