### ISSUE TITLE
Linode Marketplace App Times Out

### ISSUE THREAD

**Issue by thelecter** [Peppermint-Lab/Peppermint#49]
Marketplace app times out with no other error messages.

**Comment by potts99** [comment]
Looking into it now

**Comment by potts99** [comment]
Should be working now :)

**Comment by SamGreenwood1** [comment]
I'm having a similar issue.

**Comment by potts99** [comment]
Are you able to login into the server and get the docker logs?

**Comment by SamGreenwood1** [comment]
It doesn't load all for me. I don't even get the login page.

**Comment by potts99** [comment]
As in are you able to log into the linode instance? and run 

```
docker logs peppermint
```

**Comment by SamGreenwood1** [comment]
Works now, I think Linode's docs are just wrong. Am I supposed to have to enter the port when I'm accessing it?

**Comment by potts99** [comment]
By default yeah, unless you put it behind a reverse project

**Comment by SamGreenwood1** [comment]
Is the screenshot that up there an old release or the new one you're working on? The UI I see doesn't match the screenshot in the Linode docs.

**Comment by SamGreenwood1** [comment]
What webserver is it based on?

**Comment by potts99** [comment]
The linode docs are a bit out of date yes, currently it uses expressjs

**Comment by SamGreenwood1** [comment]
Hey again, I'm still having the same issue. Also, Linode is saying that it's using all of it's CPU allocation, what tier do you recommend?

**Comment by SamGreenwood1** [comment]
I got it working. Seems link there was some kind of issue with the Linode's network connection. I spun up a new one and it's working. Also, how'd I point my domain to it?

**Comment by potts99** [comment]
a subdomain or a primary, like example.com

**Comment by potts99** [comment]
subdomain take a lot at - https://docs.peppermint.sh/proxy

**Comment by SamGreenwood1** [comment]
Where's the peppermint.conf supposed to be saved?

**Comment by potts99** [comment]
/etc/nginx/conf.d

**Comment by SamGreenwood1** [comment]
Is there a way to assign that subdomain to statically be the Peppermint instance's URL and not just be a forward?

**Comment by SamGreenwood1** [comment]
How do I delete the default admin user?

**Comment by potts99** [comment]
you cant just change the password :)

**Comment by SamGreenwood1** [comment]
ok
