### ISSUE TITLE
can't create, delete or modify client

### ISSUE THREAD

**Issue by Ned-Comet** [Peppermint-Lab/Peppermint#52]
peppermint | PrismaClientValidationError: Argument id: Got invalid value NaN on prisma.updateOneClient. Provided Float, expected Int.
peppermint | Argument number: Got invalid value 12345678 on prisma.updateOneClient. Provided Int, expected String or NullableStringFieldUpdateOperationsInput or Null.
peppermint | 
peppermint |     at Document.validate (/usr/src/app/node_modules/@prisma/client/runtime/index.js:32546:19)
peppermint |     at NewPrismaClient._executeRequest (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34652:17)
peppermint |     at consumer (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34597:23)
peppermint |     at /usr/src/app/node_modules/@prisma/client/runtime/index.js:34599:47
peppermint |     at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
peppermint |     at NewPrismaClient._request (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34599:25)
peppermint |     at Object.then (/usr/src/app/node_modules/@prisma/client/runtime/index.js:34707:39)
peppermint |     at runMicrotasks (<anonymous>)
peppermint |     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
peppermint |   clientVersion: '2.25.0'
peppermint | }

**Comment by potts99** [comment]
will sort this asap

**Comment by potts99** [comment]
Done in latest build :)
