### ISSUE TITLE
Website SSL issue

### ISSUE THREAD

**Issue by scottdavidcraig** [Peppermint-Lab/peppermint#53]
Hey folks. 

An issue with your website's SSl cert is making your website inaccessbile. Also, when you visit the plain http version there's a 404 with the following message

"Code: DEPLOYMENT_NOT_FOUND ID: lhr1::8p4pc-1635892770606-bfaadd4fbaed
www.peppermint.sh might be available. Click here to learn how to assign it to a project."

FYI

**Comment by potts99** [comment]
New site live, thank you :)
