### ISSUE TITLE
SSO support (OIDC, SAML, LDAP)

### ISSUE THREAD

**Issue by argonaut-network** [Peppermint-Lab/peppermint#58]
Hello from Reddit! I'm just putting an official request here that can be actioned upon. I'd love to see SSO of some form (OIDC, SAML, or LDAP, namely) implemented in this project. Most teams who are using ticketing platforms will not wish to rely on the internal authentication of Peppermint for security and convenience reasons.

**Comment by potts99** [comment]
Totally get that, i'm looking at implementing keycloak support that offers SSO in a self hosted environment

**Comment by sama8** [comment]
If relevant -> [SAML Jackson](https://github.com/boxyhq/jackson)

**Comment by potts99** [comment]
Thought i was about to be baited hard

**Comment by potts99** [comment]
Working under next branch with keycloak SSO - out in next release
