### ISSUE TITLE
Basic Email notifications support

### ISSUE THREAD

**Issue by potts99** [Peppermint-Lab/peppermint#66]
Add support to sending when certain jobs are completed 

- Ticket Creation / Ticket completion 
- Client Creation
- User Creation / User password reset from log in page / user password updated by admin

Editor to allow for custom layout to be added to email

**Comment by potts99** [comment]
-  Tickets -> create and status change 
- User -> Account creation 
- Client -> Account creation

**Comment by potts99** [comment]
Basic Ticket create & status change done

**Comment by colttt** [comment]
it should be possible to configure notifications in my profile

**Comment by potts99** [comment]
Yeah we'll be adding the option to be able to enable of disable different notification types

**Comment by potts99** [comment]
- added section in profile settings to turn toggle various notifications

**Comment by potts99** [comment]
implemented under next branch - available upcoming release
