### ISSUE TITLE
fetch mails from imap and create a ticket

### ISSUE THREAD

**Issue by colttt** [Peppermint-Lab/peppermint#78]
Hello,

it would be really nice if peppermint can fetch mails from an imap-account and create tickets based on this

**Comment by potts99** [comment]
Nice suggestion, will add this to the list

**Comment by towbsen** [comment]
is there still no update? email fetch would be the best function ever for creating tickets ;-)

**Comment by xoniq** [comment]
I think this project died a bit. Last interaction since february. Also need something like this.

**Comment by potts99** [comment]
working under the next branch, i work full time, was aiming to get a feature release at the end of july but now aiming for the end of august

**Comment by towbsen** [comment]
Oh nice!Am 02.08.2022 um 12:39 schrieb Jack Andrews ***@***.***>:﻿
working under the next branch, i work full time, was aiming to get a feature release at the end of july but now aiming for the end of august

**Comment by e0xify** [comment]
is this implemented yet?

**Comment by potts99** [comment]
Nearly implemented under next branch - will be in next release

**Comment by e0xify** [comment]
> Nearly implemented under next branch - will be in next release  

Allright thanks,

Looks really nice so far but to use it i need the IMAP Feature. Any time Plan for this since last Update was August 22?

**Comment by potts99** [comment]
>  Any time Plan for this since last Update was August 22?

Sorted out my schedule recently, commiting 2-3 hours per day day now. Looking at a big release at the end of month. reddit posts etc.

**Comment by e0xify** [comment]
> >  Any time Plan for this since last Update was August 22?
> 
> Sorted out my schedule recently, commiting 2-3 hours per day day now. Looking at a big release at the end of month. reddit posts etc. 

Thanks for your effort!

**Comment by potts99** [comment]
@e0xify I have this working under the Next branch, nothing on docker yet but if you want to spin it up locally then you could give it ago.

Not production friendly yet but working on it

**Comment by e0xify** [comment]
Thanks, just checked it. I need the docker variant since im already on MySQL and dont want to add another DB system

**Comment by potts99** [comment]
Will be end of the month as im looking at a nice release

SSO
IMap emails
UI improvements 
Email notifications
slack support
Rich discord support

**Comment by e0xify** [comment]
> Will be end of the month as im looking at a nice release
> 
> SSO
> IMap emails
> UI improvements 
> Email notifications
> slack support
> Rich discord support

Any Update on the time plan?
Also will there be an automatic Reply that Ticket Nr xxxx was created for the imap Feature

**Comment by taylorgibb** [comment]
Hi @potts99 hope you are well, we really want to implement Peppermint and abandon Freshdesk, but this feature is critical for us. Is there any update on this ? Is there a list of outstanding tasks for the next release that you want help with ?

Thanks for all the amazing work on this.

**Comment by taylorgibb** [comment]
Is there any update on this  ?
