### ISSUE TITLE
Queue support

### ISSUE THREAD

**Issue by colttt** [Peppermint-Lab/peppermint#79]
As a good ticket system we need different queues for different teams.
It should also be possible that the tickets will be create in the queue based on the receiver (see also #78)

**Comment by potts99** [comment]
I don't understand what you mean sorry

**Comment by colttt** [comment]
OK, let's try to explain it ;-)
you've different departments, all departments are using this ticketsystem/helpdsksystem and every one has its own functional mail address: purchasing@example.de, it-support@example.de, office@example.de etc..
every department has its own queue and just see the tickets in this queue (here we also need a right management).

**Comment by potts99** [comment]
I get you, so users can see a general queue, specific queue, such as level 1, level 2, as well as there own tickets

**Comment by potts99** [comment]
Implementing under next branch
