### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by iSaluki** [Peppermint-Lab/Peppermint#8]
Hi,

Is it known if this will run on ARM devices? And if they are unsupported, would it be possible for either an ARM version or for some advice on how I could port it to ARM?

Appreciate you taking the time to make this!

**Comment by potts99** [comment]
Currently talking to another developer who has ported his self hostable app to arm devices 😊isn't officially support yet but it will be either tonight or tomorrow

**Comment by iSaluki** [comment]
Great, thank you so much! :)

**Comment by potts99** [comment]
Hey Bud, If you want to try now, there should be an arm64 image for you

**Comment by iSaluki** [comment]
> Hey Bud, If you want to try now, there should be an arm64 image for you 

Great thanks so much! I'll get this tested out tomorrow.

**Comment by iSaluki** [comment]
Is there a copy of this on DockerHub? Not a problem if there isn't but it would save a bit of time.

**Comment by potts99** [comment]
https://hub.docker.com/repository/docker/pepperlabs/peppermint/tags?page=1&ordering=last_updated

Latest or 0.1.5-alpha are the latest version with the arm build with them

**Comment by potts99** [comment]
There is already a template docker compose file in the readme. or you can use https://pmint.dev/docs/gettingStarted

**Comment by iSaluki** [comment]
I've just tried pulling the latest docker image to one of my raspberrypis, and I got the following output:

```pi@DeltaPi:~ $ sudo docker pull pepperlabs/peppermint:latest
latest: Pulling from pepperlabs/peppermint
no matching manifest for linux/arm/v7 in the manifest list entries```

For extra reference, here is my `/proc/cpuinfo` file: [Pastebin](https://pastebin.com/esZC2qTm)

**Comment by potts99** [comment]
Should be sorted now, there should be a 64 bit image and also a 32 bit arm image

**Comment by iSaluki** [comment]
Seems to be working, just having some issues with Docker so I'll update you soon.

**Comment by potts99** [comment]
I think I know what error you was having :) 

If you download the latest image it should be fixed

**Comment by quaintdev** [comment]
Thanks for creating Peppermint. 

I just wanted to know where is the docker image for arm64? The docker hub still lists amd64 only.
