### ISSUE TITLE
[Request] Update port numbers in various document locations

### ISSUE THREAD

**Issue by kmanwar89** [Peppermint-Lab/peppermint#80]
[SOLVED??]

After posting, I thought to modify the docker-compose file's base URL value from _http://localhost_ to _http://localhost:5000_. This seemed to do the trick and the application is now correctly loading. I checked the documentation and noticed the discrepancy: the Getting Started page on the [_docs.peppermint.sh_](https://docs.peppermint.sh/) website does not include the port number in the compose file. This must have been where I copied it from.  

I also noticed the _docker-compose_ files in the actual repository all have different port numbers:

* The README mentions port 5000
* docker-compose.dev.yml mentions port 5001
* docker-compose.staging mentions port 8000
* docker-compose.yml mentions port 5001

Is there any reason they aren't all consistent? Perhaps this is a lack of understanding on my part, but I hope my experience accurately captures the kinds of questions a new user may face.

# Original post below

Hi all,

I've heard a lot about this project from the /r/selfhosted Reddit page, so I wanted to give it a try.

I'm currently trying to run it from my Linux Mint 20.04 desktop and am receiving the following errors after attempting to login with the provided default credentials:

![image](https://user-images.githubusercontent.com/11323060/152716263-441fa7e0-a602-4c02-8543-ee8cb0b968b3.png)

Just to rule out any issues on my local machine, I followed the same process to install on my server machine, which has multiple other services running on it without issues. The server is running Ubuntu Server 21.10. In both instance, the result is the same as shown in the screenshot above, and the docker logs contain the following messages immediately after loading the main page:

```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80 {
  error: {
    message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80',
    stack: 'FetchError: request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80\n' +
      '    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1461:11)\n' +
      '    at ClientRequest.emit (events.js:400:28)\n' +
      '    at Socket.socketErrorListener (_http_client.js:475:9)\n' +
      '    at Socket.emit (events.js:400:28)\n' +
      '    at emitErrorNT (internal/streams/destroy.js:106:8)\n' +
      '    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:82:21)',
    name: 'FetchError'
  },
  path: 'csrf',
  header: {
    host: '192.168.1.196:5000',
    connection: 'keep-alive',
    'upgrade-insecure-requests': '1',
    'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36',
    accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
    'sec-gpc': '1',
    referer: 'http://192.168.1.196:5000/',
    'accept-encoding': 'gzip, deflate',
    'accept-language': 'en-US,en;q=0.9',
    cookie: 'next-auth.csrf-token=90da3b9b4598ad84915c78e066c3e80d58097b04627ce8010b39159a9a06703e%7C22b35255cc213368fd8569b04233e1473909018618a734ec290ef39e981acf88; next-auth.callback-url=http%3A%2F%2Flocalhost'
  },
  message: 'request to http://localhost/api/auth/csrf failed, reason: connect ECONNREFUSED 127.0.0.1:80'
}
undefined
```

One interesting thing to note is that even with it running on a remote machine, it still is trying to redirect after logging in to _localhost_, which obviously wouldn't work. I feel confident that I do not have any other services running that are using the same ports:

```
kadar@shadowserve:~/snap/docker/peppermint$ sudo netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      754/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      896/sshd: /usr/sbin 
tcp6       0      0 :::22                   :::*                    LISTEN      896/sshd: /usr/sbin 
udp        0      0 127.0.0.53:53           0.0.0.0:*                           754/systemd-resolve 
```

```
kadar@shadowserve:~/snap/docker/peppermint$ dps
CONTAINER ID   IMAGE                          COMMAND                  CREATED         STATUS         PORTS                                                 NAMES
1bc559d02c8c   pepperlabs/peppermint:latest   "docker-entrypoint.s…"   5 minutes ago   Up 3 seconds   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp, 5001/tcp   peppermint
e62691081585   postgres:latest                "docker-entrypoint.s…"   5 minutes ago   Up 5 minutes   5432/tcp                                              postgres
```

Attempting to login using default credentials results in the screenshot above. Appreciate any help in troubleshooting and resolving this, and happy to provide more information, thanks!

**Comment by Gsirron** [comment]
Hi, Had the same issue using docker compose, Updating BASE_URL to "http://localhost:5001" in all docker files fixed it

**Comment by potts99** [comment]
Apologies, will update all now to 5001

**Comment by potts99** [comment]
All now should be the same

**Comment by kmanwar89** [comment]
Hi @potts99  - the documentation still shows port 5000 in several places:

* docs.peppermint.sh - https://docs.peppermint.sh/
* The github page readme - https://github.com/Peppermint-Lab/peppermint

Everything should be 5001, correct?

**Comment by potts99** [comment]
Must have forgotten to do this, docs overhaul is coming soon also
