### ISSUE TITLE
Transfering Tickets to different Engineers not working

### ISSUE THREAD

**Issue by dieideeistgut** [Peppermint-Lab/peppermint#82]
Hello,

fist up - thanks for all this work! I really welcome the simplicity which gets rid of all the stuff we don't need or want (ツ)

So i've spun up an installation today using Docker (Docker-Compose) with a nginx-proxy in front of it (jwilder/nginx-proxy). Everything seemed nice on the first tests here. Creation of users, clients and tickets is working nicely as expected.

I am not able to change the engineers/asignees on any Tickets. I checked development-env, logs & browserconsole but could not get my hands on any useful logging or error. 

Is this a mistake on my side (which i assume (ツ) )? Thanks!

**Comment by potts99** [comment]
Interesting, properly just a bug on my side, will take a look now

**Comment by potts99** [comment]
@dieideeistgut Fix this, typo on my end, building new docker image building now

```
docker stop peppermint
docker rm peppermint
docker-compose up -d
```

Should get you the new image

**Comment by dieideeistgut** [comment]
Thanks a ton! Works brilliantly now. Will fork source and add de_DE-lang soon ;)

**Comment by potts99** [comment]
Dammm, impressive! Not thought about ii8 yet

**Comment by dieideeistgut** [comment]
@potts99 - Heya 👋 - would a simple i18n implementatio via next-translate be sufficient enough? Made a fork [with my i18n test here](https://github.com/dieideeistgut/peppermint/tree/feature/i18n ). i always prefer simplicity but i am curious about your thoughts.

**Comment by potts99** [comment]
Lookin at it now

**Comment by potts99** [comment]
Good start! Can you make a PR so i can maybe make it into a branch and also work on it myself

**Comment by dieideeistgut** [comment]
Sweet. Currently adding an option for the user to select language in his settings. Created PR with exactly that state of repo. You want the PR in a specific branch? Feel free to deny/delete the PR and tell me what you want.
Currently struggling with prisma and my addition of a language-setting on per-user-basis. ;)

**Comment by potts99** [comment]
yeah no worries i'll take a look over, might have potentially use some state management for that or add a field to the user in the db schema and save it into a cookie

**Comment by dieideeistgut** [comment]
Managed to upgrade db schema already. I just want the settings field populated now into the user-settings page. Will supply new PR once tested. ;)
