### ISSUE TITLE
Change ticket priority

### ISSUE THREAD

**Issue by kwschnei** [Peppermint-Lab/peppermint#83]
Currently there is no way to change the priority of a ticket. This is a very useful feature as the initial ticket creator  may mischaracterize it. This becomes even more useful when you implement ticket creation by non-logged in individuals.

**Comment by potts99** [comment]
Good Thinking, on it :)

**Comment by potts99** [comment]
Feature moved to next branch :) should be on master next couple of days. Thank you :)
