### ISSUE TITLE
Error when creating new user

### ISSUE THREAD

**Issue by JBetts97** [Peppermint-Lab/peppermint#84]
### Replication steps:
1. Login to the admin account and go to the dashboard
2. Click on users at the bottom left
3. Click new user to create a new user
4. Type in any user information and press save
5. Observe error in docker console.

### Screenshots:
![image](https://user-images.githubusercontent.com/38386086/153719995-0693f59b-ff19-43fc-a00b-9e4e9d16d75d.png)

**Comment by potts99** [comment]
Fixed, building new image now, all need todo is delete old docker image and docker-compose up and should be sound

**Comment by JBetts97** [comment]
Hi @potts99,

No worries - Thanks for the fix!
I did a ``git pull`` followed by a ``docker-compose --build`` and can confirm this bug is now resolved 👍🏻

**Comment by potts99** [comment]
No worries, apologies for that, fixed one bug and create another!! Need to get some integrated testing

**Comment by chronopoulos** [comment]
i have the same issue, but i installed from the linode marketplace. how can i fix this? i can't find a git repo to pull on.

**Comment by potts99** [comment]
This is the repo to pull from?

**Comment by chronopoulos** [comment]
thanks, i mean: from which directory would i run "git pull", on the server instance? in other words, how does the git repo relate to the docker, in the linode marketplace image?

**Comment by chronopoulos** [comment]
still having this issue, this time from a fresh install on debian 11:

- Installed docker and docker-compose
- cloned this master repo, as of 60f6d5
- ran docker-compose up from the top-level repo
- go to localhost:5001, log in with admin@admin.com and 1234
- go to Users > New User, fill in info, hit Save. nothing happens. no output in docker console
- (same for Clients > New Client)

i feel like i am missing something obvious here? how do i get the bug fix from feb 13?

**Comment by potts99** [comment]
hmmm let me test that for you

**Comment by codywarmbo** [comment]
Same error, new install. Cannot create new user or admin user. Can change admin user info. Also cannot create tickets...

**Comment by kenrad24** [comment]
> Same error, new install. Cannot create new user or admin user. Can change admin user info. Also cannot create new clients.

I'm seeing the same issue

**Comment by potts99** [comment]
Hey guys, 

Can anyone share any info on this? I just tripled checked with a fresh install and i can create just fine both new users and new clients

**Comment by potts99** [comment]
I will push a new build just in case

**Comment by mayanez** [comment]
I'm also seeing this. I just did a plain install. Nothing in the logs points to an error.

**Comment by potts99** [comment]
weird, are you pulling from main branch? will take a look again now
