### ISSUE TITLE
One click install

### ISSUE THREAD

**Issue by sharky-cpu** [Peppermint-Lab/Peppermint#9]
hey 👋

this looks like a super cool project and I would really love to try it out. I'm looking to install it on a Raspberry Pi, but I'm not quite sure how to do that. would it be possible for you to create some kind of install script or something that would allow me to get this setup?

**Comment by potts99** [comment]
Sure thing bud, have you ever used docker?

**Comment by sharky-cpu** [comment]
I've heard of it and I have a basic understanding of how it works (the theory behind it).

**Comment by potts99** [comment]
No worries, Just waiting on someone testing the arm image for docker so i'll let you know when its working :)

**Comment by potts99** [comment]
Hey bud, 

if you want to 

wget https://raw.githubusercontent.com/Peppermint-Lab/Peppermint/master/install.sh

and then bash install.sh

This should install docker and run the docker-compose for you :)

you just need to go to your device i.p and then port 5000
