### ISSUE TITLE
Running with a dedicated standalone Postgres instance on a custom port

### ISSUE THREAD

**Issue by rusty1281** [Peppermint-Lab/peppermint#91]
Hello,

would it be possible to allow this solution to use an already running Postgres instance on a custom port?

Thank you in advance!

**Comment by rusty1281** [comment]
Any info on this? 

tnx

**Comment by potts99** [comment]
Hi! Sorry for the delay, but yeah there should be no issue doing this, just need to specify the url in the compose file and remove the Postgres section

**Comment by potts99** [comment]
So db-host would be the URL and then you would alter the other fields accordingly

**Comment by rusty1281** [comment]
> So db-host would be the URL and then you would alter the other fields accordingly

Hello!

Tnx for your reply. I think when I tried it few weeks back in for of db_ip:port it don’t work. Can’t recall tbh but I will have to do it again. 

So is that format for the db_host parameter correct? Just to add the port at the end or is there some other way to make this work?

Tnx again for your time!

**Comment by potts99** [comment]
I'll be home in like 30 mins and I'll write an example yml file :)

**Comment by rusty1281** [comment]
> I'll be home in like 30 mins and I'll write an example yml file :)

Cool! Tnx again!

**Comment by rusty1281** [comment]
Just wanted to update on this matter.

Was just testing it again and found DATBASE_URL in the Docs section: https://docs.peppermint.sh/contributions

Worked like a charm. Tnx again!
