### ISSUE TITLE
Reverse proxy for subdirectory as well as for subdomain

### ISSUE THREAD

**Issue by gabrielctn** [Peppermint-Lab/peppermint#92]
Hi,

I tried installing Peppermint with the docker-compose file provided behind my Apache reverse proxy (the url looks like: https://www.mywebsite.fr/peppermint), but as I understand in the documentation, the reverse proxy works only for subdomain configurations, not subdirectories ?
When I install it then I get the following in the browser:
https://user-images.githubusercontent.com/25644865/156941506-85f8f687-9d8b-4f51-a76c-646cc67850d0.mov

Is there a (simple) way to get it work for subdirectories as well ?

Thank you for your work !

**Comment by potts99** [comment]
Hiya, thanks for trying us out! Not managed to test out subdirectories but i can add it too the pile :)
