### ISSUE TITLE
Few issues after an initial use

### ISSUE THREAD

**Issue by rusty1281** [Peppermint-Lab/peppermint#95]
Safari browser user here. Adding a ticket and working on it results in ticket getting created. 

Still moving from sections will not result is changes being visible unless you do a manual refresh inside the browser. 

Also, this happens for example when flagging ticket as completed. Manual refresh changes the status eventually. 

Could there be a generate ticket number and not just name of it? 

One more thing that I noticed is that multiple activities are not flagged as a separate entry with a time stamp?

Finally, using the app in a mobile format does not remove the left side navigation after switching from let’s say Dashboard to Tickets or any other element. The menu stays even the screen has changed. 

Tnx for your hard work so far!

**Comment by potts99** [comment]
Thank you - Will look into these issues :)

**Comment by potts99** [comment]
These are all now implemented and fixed
